name: PERN Stack CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install backend dependencies
        working-directory: ./server/ewaste-reporting
        run: npm install

      - name: Run backend tests
        working-directory: ./server/ewaste-reporting
        run: npm test

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    needs: backend # Run after backend succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies
        working-directory: ./client-side
        run: npm install

      - name: Run frontend tests
        working-directory: ./client-side
        run: npm test

      - name: Build frontend
        working-directory: ./client-side
        run: npm run build
